#!/bin/sh

# PROVIDE: SABR
# REQUIRE: LOGIN
# KEYWORD: shutdown

#
# Add the following lines to /etc/rc.conf.local or /etc/rc.conf
# to enable this service:
#
# SABR_enable (bool): Set to NO by default. Set this variable to YES if you want to enable SABR service.
# SABR_config (path): Set to /usr/local/etc/SABR.conf by default.
# SABR_user:  The user account SABR daemon runs as. It uses 'root' user by default.
# SABR_group: The group account SABR daemon runs as. It uses 'wheel' group by default.
# SABR_datadir (str): Default to "/var/db/SABR". Base data directory.

. /etc/rc.subr

name=SABR
rcvar=SABR_enable

: ${SABR_enable:=NO}
: ${SABR_config=/usr/local/etc/SABR.conf}
: ${SABR_datadir=/var/db/SABR}
: ${SABR_user="root"}
: ${SABR_group="wheel"}

required_files=${SABR_config}
command=/usr/local/bin/SABRd
SABR_chdir=${SABR_datadir}
pidfile="${SABR_datadir}/SABRd.pid"
stop_cmd=SABR_stop
command_args="-conf=${SABR_config} -datadir=${SABR_datadir} -daemon -pid=${pidfile}"
start_precmd="${name}_prestart"

SABR_create_datadir()
{
	echo "Creating data directory"
	eval mkdir -p ${SABR_datadir}
	[ $? -eq 0 ] && chown -R ${SABR_user}:${SABR_group} ${SABR_datadir}
}

SABR_prestart()
{
	if [ ! -d "${SABR_datadir}/." ]; then
		SABR_create_datadir || return 1
	fi
}

SABR_requirepidfile()
{
	if [ ! "0`check_pidfile ${pidfile} ${command}`" -gt 1 ]; then
		echo "${name} not running? (check $pidfile)."
		exit 1
	fi
}

SABR_stop()
{
    SABR_requirepidfile

	echo "Stopping ${name}."
	eval ${command} -conf=${SABR_config} -datadir=${SABR_datadir} stop
	wait_for_pids ${rc_pid}
}

load_rc_config $name
run_rc_command "$1"
